version: '20160205.0.{build}'
build_script:
    - ps: choco pack msys2-installer.nuspec --version="20160205.0.0"

artifacts:
    - path: .\*.nupkg

deploy:
    -   provider: Environment
        name: Chocolatey
        on:
            branch: master
            APPVEYOR_REPO_TAG: true
